title: ConfigForQuery
type: object
properties:
  sort:
    title: Sort
    type: array
    items:
      maxItems: 2
      minItems: 2
      type: array
      items:
      - type: string
      - type: integer
  limit:
    title: Limit
    type: integer
