openapi: 3.0.0
info:
  title: Dokumentacja API serwisu iMSiG.pl - KRS API, MSIG API, KRZ API
  version: 1.0.179
  description:
    $ref: common/info_description.md
  x-logo:
    url: https://www.imsig.pl/layout/monitor_sadowy_i_gospodarczy.png
    altText: iMSiG.pl
  contact:
    url: https://www.imsig.pl
    name: MGBI sp. z o.o.
    email: info@imsig.pl
tags:
- x-displayName: Dokumenty
  name: documents
  description:
    $ref: krs_rdf/descriptions/tag_documents.md
- x-displayName: Dane finansowe
  name: financial_data
  description:
    $ref: krs_rdf/descriptions/tag_financial_data.md
- x-displayName: Ogłoszenia
  name: announcements
  description:
    $ref: msig/descriptions/tag_announcements.md
- x-displayName: Aktualizacje
  name: updates
  description:
    $ref: other/descriptions/tag_updates.md
- x-displayName: Announcements
  name: announcements_iapi
  description:
    $ref: ins_api/descriptions/tag_announcements.md
- x-displayName: Filters
  name: filters_iapi
  description:
    $ref: ins_api/descriptions/tag_filters.md
- x-displayName: Reports
  name: reports_iapi
  description:
    $ref: ins_api/descriptions/tag_reports.md
- x-displayName: Dicts
  name: dicts_iapi
  description:
    $ref: ins_api/descriptions/tag_dicts.md
- x-displayName: Users
  name: users_iapi
  description:
    $ref: ins_api/descriptions/tag_users.md
- x-displayName: Updates
  name: updates_iapi
  description:
    $ref: ins_api/descriptions/tag_updates.md
- x-displayName: Params
  name: params_iapi
  description:
    $ref: ins_api/descriptions/tag_params.md
- x-displayName: Monitors
  name: monitors_iapi
  description:
    $ref: ins_api/descriptions/tag_monitors.md
- x-displayName: Notifications
  name: notifications_iapi
  description:
    $ref: ins_api/descriptions/tag_notifications.md
x-tagGroups:
- name: KRS RDF API
  tags:
  - documents
  - financial_data
- name: MSiG API, KRZ API
  tags:
  - announcements
  - updates
- name: MSIG API V2
  tags:
  - monitors_iapi
  - reports_iapi
  - filters_iapi
  - notifications_iapi
  - users_iapi
  - announcements_iapi
  - dicts_iapi
  - updates_iapi
  - params_iapi
paths:
  /v2/filters:
    get:
      $ref: ins_api/paths/actual-user-filters-v2-filters-GET.yaml
    post:
      $ref: ins_api/paths/create-filter-v2-filters-POST.yaml
    delete:
      $ref: ins_api/paths/filter-v2-filters-DELETE.yaml
  /v2/monitors/{id}:
    get:
      $ref: ins_api/paths/user-monitor-by-id-v2-monitors-id-GET.yaml
    patch:
      $ref: ins_api/paths/user-monitors-v2-monitors-id-PATCH.yaml
  /v2/users/me:
    get:
      $ref: ins_api/paths/current-user-v2-users-me-GET.yaml
  /v2/dicts/announcement-categories:
    get:
      $ref: ins_api/paths/announcement-category-v2-dicts-announcement-categories-GET.yaml
  /v2/notifications:
    get:
      $ref: ins_api/paths/notifications-v2-notifications-GET.yaml
  /v2/notifications/{id}:
    get:
      $ref: ins_api/paths/user-notification-by-id-v2-notifications-id-GET.yaml
  /v2/updates/{id}:
    get:
      $ref: ins_api/paths/update-by-id-v2-updates-id-GET.yaml
  /v2/reports:
    get:
      $ref: ins_api/paths/reports-v2-reports-GET.yaml
    post:
      $ref: ins_api/paths/create-report-v2-reports-POST.yaml
    delete:
      $ref: ins_api/paths/reports-v2-reports-DELETE.yaml
  /v2/reports/{report_id}:
    get:
      $ref: ins_api/paths/report-by-id-v2-reports-report-id-GET.yaml
  /v2/filters/{id}:
    get:
      $ref: ins_api/paths/user-filter-by-id-v2-filters-id-GET.yaml
    patch:
      $ref: ins_api/paths/user-filters-v2-filters-id-PATCH.yaml
  /v1/rdf/financialData:
    get:
      $ref: krs_rdf/paths/financial-data-GET.yaml
  /v2/dicts/report-statuses:
    get:
      $ref: ins_api/paths/report-statuses-v2-dicts-report-statuses-GET.yaml
  /v2/dicts/report-types:
    get:
      $ref: ins_api/paths/types-v2-dicts-report-types-GET.yaml
  /v1/rdf/documents:
    get:
      $ref: krs_rdf/paths/documents-GET.yaml
  /v2/dicts/announcement-fields:
    get:
      $ref: ins_api/paths/fields-v2-dicts-announcement-fields-GET.yaml
  /v2/dicts/report-formats:
    get:
      $ref: ins_api/paths/report-formats-v2-dicts-report-formats-GET.yaml
  /v1/msig/checkNumbers:
    post:
      $ref: msig/paths/check-numbers-POST.yaml
  /v1/msig/announcements:
    get:
      $ref: msig/paths/announcements-GET.yaml
  /v2/reports/{report_id}/download:
    get:
      $ref: ins_api/paths/download-report-by-id-v2-reports-report-id-download-GET.yaml
  /v1/msig/updates:
    get:
      $ref: msig/paths/updates-GET.yaml
  /v2/params:
    get:
      $ref: ins_api/paths/actual-user-params-v2-params-GET.yaml
  /v2/announcements:
    get:
      $ref: ins_api/paths/announcements-v2-announcements-GET.yaml
  /v2/announcements/{id}:
    get:
      $ref: ins_api/paths/announcement-by-id-v2-announcements-id-GET.yaml
  /v2/updates:
    get:
      $ref: ins_api/paths/updates-v2-updates-GET.yaml
  /v2/monitors:
    get:
      $ref: ins_api/paths/monitors-v2-monitors-GET.yaml
    post:
      $ref: ins_api/paths/create-monitor-v2-monitors-POST.yaml
    delete:
      $ref: ins_api/paths/monitors-v2-monitors-DELETE.yaml
components:
  securitySchemes:
    $ref: common/security-schemes.yaml
  schemas:
    $ref: common/schemas.yaml
