# name of main file
spec: openapi.yaml

# map endpoints path to directories (it support only "*" other sink)
path-to-directory:
  /v1/msig: msig
  /v2: ins_api
  "*": other
# map tags to directories (it supports star prefix, suffix, completions)
tag-to-directory:
  financial_data: krs_rdf
  announcements: msig
  "*_iapi": ins_api
  "*": other
