openapi: 3.0.0
info:
  title: Dokumentacja API serwisu iMSiG.pl - MSIG API, KRZ API
  version: '1.0.0'
  x-logo:
    url: 'https://www.imsig.pl/layout/monitor_sadowy_i_gospodarczy.png'
    altText: iMSiG.pl
  description:
    $ref: description.md
  contact:
    name: MGBI sp. z o.o.
    url: 'https://www.imsig.pl'
    email: info@imsig.pl

tags:
  - name: announcements
    x-displayName: Ogłoszenia
    description:
      $ref: msig/descriptions/announcements.md

  - name: updates
    x-displayName: Aktualizacje

x-tagGroups:
  - name: MSiG API, KRZ API
    tags:
      - announcements
      - updates

paths:
  /v1/msig/announcements:
    get:
      $ref: msig/paths/get-announcements.yaml
  /v1/msig/updates:
    get:
      $ref: msig/paths/get-updates.yaml
  /v1/msig/checkNumbers:
    post:
      $ref: msig/paths/check-numbers.yaml

components:
  securitySchemes:
    $ref: common/security-schemes.yaml
